# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 라영채 (Ra Young Chae, Elya)
title: 
email: yc.ra.elya@gmail.com
website: velog.io/@lack12

# Dark Mode (true/false/never)
darkmode: true

# Social links
# twitter_username: facespics
github_username: ElyaSetinal
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
about_title: Simply Introduce
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  나이 : 31세 (1992년생)
  
  최종학력 : 4년제 대학 졸업

  현 거주지 : 경기 화성시

  병역사항 : 육군 만기 전역(2012.03 - 2013.12) 

  코드를 통하여 알고리즘을 구현하고, 동작하는 모습에 보람과 기쁨을 느낍니다.
  아직 많은 것을 알고있지는 않지만, 구현하기 위해 방법을 찾고, 적용하고, 동작하며 생기는 모든 일들이 나의 경험이고 배움이다 라고 생각하며 공부하고, 개발하고 있습니다.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 대영산전(주)창원공장
        link: www.dysj.co.kr
        # link_text: boringcompany.com
        sub_title: 기업부설연구소 연구원 / 제어기술부 대리
        caption: 2018.05 - 2021.12(3년 8개월)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            - 주요 업무
              - R&D
              - 사내제품 검사 장비 개발 및 아웃소싱 장비 개발 참여
              - 제품 설계 및 프로그래밍

      - layout: left
        title: 포스PC방
        link: 
        # link_text: boringcompany.com
        sub_title: 아르바이트 / 정직원
        caption: 2014.09 - 2016.12(2년 3개월)
        quote: >
          
        description: | # this will include new lines to allow paragraphs
            - 주요 업무
              - 카운터 및 물품 재고 관리

  - title: Skill
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Language
        caption: 
        sub_title: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          - Used as the main : <mark>Python</mark>
          - Used at least once : <mark>C</mark>, <mark>HTML</mark>, <mark>VBA</mark>

      - layout: left
        title: Framework
        caption: 
        sub_title: 
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          - Used as the main : <mark>Django</mark>
          - Used at least once : <mark>TailwindCSS</mark>

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 창원대학교
        caption: 2011.03 - 2017.02
        sub_title: 메카트로닉스공학부 제어계측공학과
        quote: >
          경남 창원 소재 4년제 대학교
        description: | # this will include new lines to allow paragraphs
          - 졸업학점 : 3.33 / 4.5
          - 2학년 : 동아리 간부를 하며, 운영에 관한 기획이나 진행 방향등을 설계하고 실제로 진행하는 경험을 해보았습니다. 
          - 3학년, 4학년 : 캡스톤 디자인을 통해 타 학과와 협업하고, 센서와 제어기술을 사용한 스마트의류/시각장애우용 보조기구를 제작했습니다.

      - layout: left
        title: 병점고등학교
        caption: 2007.03 - 2010.02
        sub_title: 이과
        quote: >
          경기도 화성 소재 고등학교
        description: | # this will include new lines to allow paragraphs
          
  - title: Class # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: (The Origin) 백엔드 개발자 취업 아카데미 with Django
        caption: 2022.03 - 2022.05
        sub_title: Project Lion
        quote: >
          Python과 Django를 이용한 백엔드 개발 교육
        description: | # this will include new lines to allow paragraphs
          - Python 독학중 학습 방향성이 기존 틀을 벗어나지 못한다고 느껴서 수강하였습니다.
          - 격주로 진행되는 과제 및 Django를 적용한 개인 Toy Project를 수행하며 Django의 MVT 패턴 및 CRUD등 백엔드의 기초를 배웠습니다.
          - Peer Group과의 상호 피드백을 통하여 다른 개발자와 협업하고, 커뮤니케이션의 중요성을 한번 더 느낀 시간이 되었습니다.

  - title: Certificate # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: COS pro
        caption: 2021.03
        sub_title: Python 2급
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          YBM 주관

      - layout: left
        title: Toeic
        caption: 2022.03
        sub_title: 680
        quote: >
          
        description: | # this will include new lines to allow paragraphs
          LC 345, RC 335

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      비전공자로써 졸업하고, <mark>Back-End</mark> 개발자와는 거리가 있는 직군에서 일을 해왔었지만, 3년동안 팀원 및 프로젝트 참여 인원과의 커뮤니케이션 및 업무 피드백들을 통해서 소통과 협업의 중요성을 배웠습니다. 또한 제품을 설계하고 직접 만들어가면서 '그림을 그린다.' 라고 표현할 수 있는 업무의 순서나 흐름을 생각하고 직접 시행해보며 전체적인 틀을 그리고 만들며, 세부적인 내용을 하나씩 채워나가고 모르는 부분은 배워나가는 경험을 했습니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
